# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "dummy"

  config.vm.provision "shell" do |s|
	s.path = "provision.sh"
	s.args = "/vagrant/conf.d/id_rsa"
  end

  config.vm.provider :aws do |aws, override|
    aws.keypair_name = "aws-micro"
    override.ssh.private_key_path = "~/.ssh/aws-micro.pem"
    aws.instance_type = "t2.micro"
    aws.ami = "ami-5189a661"
    override.ssh.username = "ubuntu"
    aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
    aws.region = "us-west-2"
    aws.security_groups = "tub"

    # More comprehensive region config
#    aws.region_config "us-west-2a", :ami => "ami-5189a661"
  end
#  config.ssh.forward_agent = true 
  config.ssh.forward_x11 = true
end
