// Render the one-page Markdown brief for a top-ranked Web3 security problem.
//
// The brief is deliberately structured so the site owner can turn it into a
// blog post quickly:
//
//   1. TL;DR — one punchy sentence.
//   2. Why it's pressing — bullets with cited evidence.
//   3. Who's affected — concrete personas.
//   4. Evidence — deduped links with engagement metrics.
//   5. Proposed solution angles — brainstorm seeds for the blog post.
//   6. Blog hook — suggested opening sentence.
//   7. Sources used — transparent list so the post can cite primary evidence.
//
// The renderer does not try to do NLP — the crawler's job is to surface and
// rank raw evidence; the author writes the final prose. What we _do_ provide
// is a deterministic, reproducible template so every brief has the same shape.

/** @typedef {import('./cluster.mjs').PopulatedCluster & {score:number, breakdown: Record<string,number>}} RankedCluster */

const SOURCE_LABEL = {
  hackernews: 'Hacker News',
  reddit: 'Reddit',
  'ethereum-stackexchange': 'Ethereum Stack Exchange',
  'github-advisories': 'GitHub Security Advisories',
  'github-issues': 'GitHub Issues',
  'ethereum-magicians': 'Ethereum Magicians',
}

/**
 * @param {RankedCluster} cluster
 * @param {{generatedAt: string}} meta
 * @returns {string}
 */
export function renderBrief(cluster, meta) {
  const topSignals = cluster.signals.slice(0, 8)
  const sources = [...new Set(cluster.signals.map((s) => s.source))]
  const totalEngagement = cluster.signals.reduce((a, s) => a + (s.engagement || 0), 0)
  const newestAgeDays = Math.floor(
    (Date.now() - Math.max(...cluster.signals.map((s) => new Date(s.publishedAt).getTime()))) /
      86400000,
  )

  const lines = []
  lines.push(`# ${cluster.label}`)
  lines.push('')
  lines.push(
    `**Domain:** Web3 Security  ·  **Status:** Pressing  ·  **Cluster:** \`${cluster.id}\`  ·  **Score:** ${cluster.score}`,
  )
  lines.push('')
  lines.push(
    `**Gathered:** ${meta.generatedAt.slice(0, 10)}  ·  **Signals:** ${cluster.signals.length} across ${sources.length} sources  ·  **Newest signal:** ${newestAgeDays} day(s) ago`,
  )
  lines.push('')

  // TL;DR
  lines.push('## TL;DR')
  lines.push('')
  lines.push(`> ${cluster.description}`)
  lines.push('')

  // Why this is pressing
  lines.push('## Why this is pressing')
  lines.push('')
  lines.push(
    `- **Cross-source breadth.** Surfaced by **${sources.length}** independent sources (${sources
      .map((s) => SOURCE_LABEL[s] || s)
      .join(', ')}) — not a single-community echo chamber.`,
  )
  lines.push(
    `- **Volume.** ${cluster.signals.length} distinct discussions, issues, or advisories tagged this cluster in the crawl window.`,
  )
  lines.push(
    `- **Engagement.** Aggregate engagement across signals: ~${totalEngagement} upvotes/comments/severity points.`,
  )
  lines.push(
    `- **Recency.** Most recent signal is only ${newestAgeDays} day(s) old — the conversation is live.`,
  )
  lines.push(
    `- **Matched vocabulary.** Common phrases driving this cluster: ${topMatchedKeywords(cluster)
      .map((k) => '`' + k + '`')
      .join(', ')}.`,
  )
  lines.push('')

  // Who is affected
  lines.push('## Who is affected')
  lines.push('')
  for (const persona of personaHints(cluster.id)) {
    lines.push(`- ${persona}`)
  }
  lines.push('')

  // Evidence
  lines.push('## Evidence (top signals)')
  lines.push('')
  for (const sig of topSignals) {
    const label = SOURCE_LABEL[sig.source] || sig.source
    const date = sig.publishedAt?.slice(0, 10) || ''
    const eng = sig.engagement ? ` · engagement ${sig.engagement}` : ''
    lines.push(`- [${escapeTitle(sig.title)}](${sig.url}) — *${label}*, ${date}${eng}`)
    if (sig.snippet) {
      lines.push(`  > ${escapeQuote(truncate(sig.snippet, 220))}`)
    }
  }
  lines.push('')

  // Proposed solution angles
  lines.push('## Proposed solution angles (seeds for the blog post)')
  lines.push('')
  for (const angle of solutionAngles(cluster.id)) {
    lines.push(`- ${angle}`)
  }
  lines.push('')

  // Blog hook
  lines.push('## Blog hook')
  lines.push('')
  lines.push(`> ${blogHook(cluster)}`)
  lines.push('')

  // Sources used
  lines.push('## Sources referenced')
  lines.push('')
  const bySource = groupBy(cluster.signals, (s) => s.source)
  for (const src of Object.keys(bySource).sort()) {
    lines.push(`- **${SOURCE_LABEL[src] || src}** — ${bySource[src].length} signal(s)`)
  }
  lines.push('')

  lines.push('---')
  lines.push('')
  lines.push(
    '_Auto-generated by `tools/web3-intel`. Re-run with `npm run intel` to refresh. Turn this brief into a blog post by drafting the solution section and adding your personal angle — the crawler gives you evidence, not prose._',
  )
  lines.push('')

  return lines.join('\n')
}

/**
 * Combined top-level report document — a single markdown file that lists all
 * top clusters in one view, handy to skim on a phone.
 * @param {RankedCluster[]} ranked
 * @param {{generatedAt: string, totalSignals: number, perSource: Record<string, number>}} meta
 */
export function renderReport(ranked, meta) {
  const lines = []
  lines.push(`# Web3 Security — Pressing Problems Intel`)
  lines.push('')
  lines.push(`_Generated ${meta.generatedAt}_`)
  lines.push('')
  lines.push(
    `Total signals crawled: **${meta.totalSignals}**. Top **${ranked.length}** problems below.`,
  )
  lines.push('')
  lines.push('## Signals per source')
  lines.push('')
  for (const [src, n] of Object.entries(meta.perSource)) {
    lines.push(`- **${SOURCE_LABEL[src] || src}** — ${n}`)
  }
  lines.push('')
  lines.push('## Top problems')
  lines.push('')
  ranked.forEach((c, i) => {
    lines.push(`### ${i + 1}. ${c.label}`)
    lines.push('')
    lines.push(`- **Score:** ${c.score}`)
    lines.push(`- **Signals:** ${c.signals.length}`)
    lines.push(
      `- **Sources:** ${[...new Set(c.signals.map((s) => SOURCE_LABEL[s.source] || s.source))].join(', ')}`,
    )
    lines.push(`- **Brief:** [\`briefs/${c.id}.md\`](briefs/${c.id}.md)`)
    lines.push('')
    lines.push(`${c.description}`)
    lines.push('')
  })
  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Templating helpers
// ---------------------------------------------------------------------------

function topMatchedKeywords(cluster) {
  const counts = new Map()
  for (const sig of cluster.signals) {
    for (const k of sig.matchedKeywords || []) {
      counts.set(k, (counts.get(k) || 0) + 1)
    }
  }
  return [...counts.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5)
    .map(([k]) => k)
}

function groupBy(arr, fn) {
  /** @type {Record<string, any[]>} */
  const out = {}
  for (const x of arr) {
    const k = fn(x)
    ;(out[k] ||= []).push(x)
  }
  return out
}

function escapeTitle(t) {
  return String(t).replace(/\[/g, '\\[').replace(/\]/g, '\\]')
}

function escapeQuote(t) {
  return String(t).replace(/\n+/g, ' ').replace(/>/g, '&gt;')
}

function truncate(s, n) {
  const str = String(s)
  return str.length <= n ? str : str.slice(0, n - 1) + '…'
}

// Persona and solution-angle hints per cluster. These are intentionally light
// — not exhaustive blog posts. They give the author a starting point without
// pretending to be original analysis.

function personaHints(id) {
  const map = {
    'signature-phishing': [
      'End users of any EVM wallet with an ERC-20 or NFT balance.',
      'dApp frontend maintainers whose users get drained via off-protocol sigs.',
      'Wallet vendors shipping blind-signing UX.',
    ],
    'bridge-exploits': [
      'L1/L2 bridge operators and their TVL depositors.',
      'Cross-chain-native protocols (perp DEXes, yield aggregators).',
      'Users holding wrapped assets across ecosystems.',
    ],
    'oracle-manipulation': [
      'Lending and perp-DEX protocols.',
      'LPs in AMM pools referenced as price sources.',
      'Integrators blindly consuming low-liquidity price feeds.',
    ],
    'flashloan-governance': [
      'DAO-governed protocols with on-chain voting.',
      'Lending protocols exposing flashloan primitives.',
      'Yield protocols whose assumptions break within a single block.',
    ],
    reentrancy: [
      'Any protocol handling ETH transfers, ERC-777 tokens, or ERC-1155 callbacks.',
      'Vault / staking contracts with external calls in the middle of state updates.',
    ],
    'access-control': [
      'Auditors and protocol developers — the cheapest bug to find and the most embarrassing to ship.',
      'Teams using unproven deployment scripts.',
    ],
    'proxy-upgrades': [
      'Any team on OpenZeppelin Upgrades, UUPS, Diamond, or custom proxy patterns.',
      'Protocol governance trying to ship storage-layout changes safely.',
    ],
    'mev-frontrunning': [
      'Retail swappers on public mempools.',
      'Intent-based protocols and their solvers.',
      'Validators choosing between MEV-boost relays.',
    ],
    'zk-circuit-bugs': [
      'Rollup teams and their users.',
      'Projects integrating circom/halo2/plonk libraries.',
      'Auditors without ZK-specific tooling.',
    ],
    'supply-chain': [
      'Solidity / Hardhat / Foundry developers installing npm packages.',
      'Protocol teams with CI secrets and private keys on build runners.',
    ],
    'rollup-sequencer': [
      'L2 users during sequencer outages.',
      'Protocols with forced-inclusion assumptions in their safety model.',
    ],
    'account-abstraction': [
      'Smart-account wallet users and 4337 infra operators.',
      'Paymaster service providers.',
    ],
    'key-management': [
      'Retail holders.',
      'Treasury multisig operators.',
      'Teams storing deployer keys on CI.',
    ],
    'frontend-compromise': [
      'dApp users who trust the UI more than the contract.',
      'Teams relying on DNS or IPFS gateways they do not control.',
    ],
  }
  return map[id] || ['Any team or user exposed to this class of issue.']
}

function solutionAngles(id) {
  const map = {
    'signature-phishing': [
      'Wallet-side signature simulators that decode permit / permit2 / setApprovalForAll into human sentences.',
      'Domain-wide allowlists maintained by a reputation service, surfaced at the wallet UI.',
      'Session-keyed smart accounts that cap spend regardless of what gets signed.',
    ],
    'bridge-exploits': [
      'Minimize validator-set trust via native rollup bridges or ZK light clients.',
      'Independent on-chain invariant monitors that pause bridges on anomalies.',
      'Rate-limited withdrawals with time delays and refund paths.',
    ],
    'oracle-manipulation': [
      'Layered oracles combining spot + TWAP + off-chain cryptographic feeds.',
      'Circuit breakers that pause borrowing when oracle deviation exceeds thresholds.',
      'Economic-security models that price the cost of manipulation explicitly.',
    ],
    'flashloan-governance': [
      'Voting power snapshots that exclude mid-block balance changes.',
      'Mandatory timelocks on any governance action touching treasury or parameters.',
      'Per-block invariant checks enforcing reserve ratios.',
    ],
    reentrancy: [
      'Universal nonReentrant guards applied by default in project templates.',
      'Formal verification harnesses for checks-effects-interactions ordering.',
      'Static analyzers that flag callback-enabled tokens in vaults.',
    ],
    'access-control': [
      'Deployment checklists that verify ownership handoff before announcing a launch.',
      'CI jobs that statically prove every public mutating function is access-controlled.',
      'Registry of known-bad initializer patterns, wired into linters.',
    ],
    'proxy-upgrades': [
      'Upgrade simulation harnesses that diff storage layouts before approval.',
      'Canary upgrades on a fork with full invariant suite.',
      'Time-locked upgrade proposals with machine-readable diffs.',
    ],
    'mev-frontrunning': [
      'Default-on private mempool routing for retail swappers.',
      'MEV-refund programs visible directly in the swap UI.',
      'Intent-based matching with verifiable solver competition.',
    ],
    'zk-circuit-bugs': [
      'Differential fuzzing between spec and circuit implementations.',
      'Under-constraint detectors integrated into circom/halo2 toolchains.',
      'Public bug bounties specifically for soundness bugs, separately priced from correctness bugs.',
    ],
    'supply-chain': [
      'Dependency allowlists pinned by hash, enforced in CI.',
      'Ephemeral build runners with no persistent key material.',
      'Watcher bots that alert on suspicious version bumps in web3 SDKs.',
    ],
    'rollup-sequencer': [
      'Shared sequencer networks with cryptoeconomic slashing.',
      'One-click escape-hatch UIs to L1 for users stuck during outages.',
      'Monitoring dashboards that make censorship quantitative, not anecdotal.',
    ],
    'account-abstraction': [
      'Conformance test suites for bundlers and paymasters.',
      'Validation-phase static analyzers enforcing ERC-4337 storage rules.',
      'Threat models specific to delegated EOAs under EIP-7702.',
    ],
    'key-management': [
      'Default-secure deployer wallets with hardware attestation.',
      'Post-deployment key rotation playbooks for every protocol launch.',
      'Detection rules for seed-phrase exfiltration in wallet extensions.',
    ],
    'frontend-compromise': [
      'Signed frontends with content-addressed delivery.',
      'Wallet-side domain binding so signatures cannot be forwarded from a malicious UI.',
      'Public monitoring of dApp DNS and TLS changes.',
    ],
  }
  return map[id] || ['Write from your own research — no seeds yet for this cluster.']
}

function blogHook(cluster) {
  const hooks = {
    'signature-phishing':
      'Your users are one EIP-712 signature away from an empty wallet — and they will click through any modal you show them. Here is what finally moves the needle.',
    'bridge-exploits':
      'Bridges keep burning the same way. This post argues the fix is not "audit harder" — it is "trust less, and make it boring."',
    'oracle-manipulation':
      'Price feeds are the soft underbelly of DeFi. Walk through three recent exploits, and three patterns that would have killed all of them.',
    'flashloan-governance':
      'Your DAO is one flashloan away from a hostile takeover. The fix is not in Solidity — it is in how you count votes.',
    reentrancy:
      'Reentrancy is 2016\u2019s bug. Here is why it keeps shipping in 2025, and how the new variants slip past every "safe" pattern.',
    'access-control':
      'The most embarrassing bug in your protocol is also the cheapest for an attacker to find. Here is a CI recipe to make it impossible.',
    'proxy-upgrades':
      'Upgradeable contracts promised flexibility and delivered footguns. Here is how to upgrade without bricking — with a concrete diff harness.',
    'mev-frontrunning':
      'Every swap your users make is taxed by a bot they cannot see. This post names that tax and shows three ways to zero it out in 2025.',
    'zk-circuit-bugs':
      'A sound-looking proof for a false statement is the worst kind of bug. Here is why ZK auditing is still in its infancy — and what to do about it.',
    'supply-chain':
      'The attacker does not need to break your Solidity. They just need to push a patch release to a package you already trust.',
    'rollup-sequencer':
      'Your L2 is fast, cheap, and one sequencer outage away from a bad weekend. Here is the threat model nobody wants to write down.',
    'account-abstraction':
      'EIP-4337 and EIP-7702 hand users smart-account superpowers — and hand attackers a fresh surface. Here is the threat model that matters in 2025.',
    'key-management':
      'Most losses in Web3 are not clever exploits — they are stolen keys. Here is a sober playbook for teams that still think "we have a hardware wallet" is enough.',
    'frontend-compromise':
      'Your contracts are audited. Your frontend is a single DNS record away from draining your users. Here is how to close that gap.',
  }
  return (
    hooks[cluster.id] ||
    `${cluster.label} keeps showing up in the conversation. Here is what it is, why it matters, and what a pragmatic fix looks like.`
  )
}
